# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Load_img1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Load_img1_btn.setGeometry(QtCore.QRect(40, 120, 121, 31))
        self.Load_img1_btn.setObjectName("Load_img1_btn")
        self.Load_img2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Load_img2_btn.setGeometry(QtCore.QRect(40, 250, 121, 31))
        self.Load_img2_btn.setObjectName("Load_img2_btn")
        self.Load_img1_label = QtWidgets.QLabel(self.centralwidget)
        self.Load_img1_label.setGeometry(QtCore.QRect(40, 160, 111, 20))
        self.Load_img1_label.setObjectName("Load_img1_label")
        self.Load_img2_label = QtWidgets.QLabel(self.centralwidget)
        self.Load_img2_label.setGeometry(QtCore.QRect(40, 290, 111, 20))
        self.Load_img2_label.setObjectName("Load_img2_label")
        self.Img_pro_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Img_pro_box.setGeometry(QtCore.QRect(239, 79, 191, 341))
        self.Img_pro_box.setObjectName("Img_pro_box")
        self.Color_sep_btn = QtWidgets.QPushButton(self.Img_pro_box)
        self.Color_sep_btn.setGeometry(QtCore.QRect(30, 50, 131, 31))
        self.Color_sep_btn.setObjectName("Color_sep_btn")
        self.Color_tran_btn = QtWidgets.QPushButton(self.Img_pro_box)
        self.Color_tran_btn.setGeometry(QtCore.QRect(30, 110, 131, 31))
        self.Color_tran_btn.setObjectName("Color_tran_btn")
        self.Color_det_btn = QtWidgets.QPushButton(self.Img_pro_box)
        self.Color_det_btn.setGeometry(QtCore.QRect(30, 170, 131, 31))
        self.Color_det_btn.setObjectName("Color_det_btn")
        self.Blend_btn = QtWidgets.QPushButton(self.Img_pro_box)
        self.Blend_btn.setGeometry(QtCore.QRect(30, 230, 131, 31))
        self.Blend_btn.setObjectName("Blend_btn")
        self.Img_smo_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Img_smo_box.setGeometry(QtCore.QRect(450, 80, 221, 341))
        self.Img_smo_box.setObjectName("Img_smo_box")
        self.Gau_btn = QtWidgets.QPushButton(self.Img_smo_box)
        self.Gau_btn.setGeometry(QtCore.QRect(20, 50, 171, 31))
        self.Gau_btn.setObjectName("Gau_btn")
        self.Bil_btn = QtWidgets.QPushButton(self.Img_smo_box)
        self.Bil_btn.setGeometry(QtCore.QRect(20, 130, 171, 31))
        self.Bil_btn.setObjectName("Bil_btn")
        self.Med_btn = QtWidgets.QPushButton(self.Img_smo_box)
        self.Med_btn.setGeometry(QtCore.QRect(20, 210, 171, 31))
        self.Med_btn.setObjectName("Med_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Load_img1_btn.setText(_translate("MainWindow", "Load Image 1"))
        self.Load_img2_btn.setText(_translate("MainWindow", "Load Image 2"))
        self.Load_img1_label.setText(_translate("MainWindow", "No image loaded"))
        self.Load_img2_label.setText(_translate("MainWindow", "No image loaded"))
        self.Img_pro_box.setTitle(_translate("MainWindow", "1. Image Processing"))
        self.Color_sep_btn.setText(_translate("MainWindow", "1.1 Color Separation"))
        self.Color_tran_btn.setText(_translate("MainWindow", "1.2 Color Transformation"))
        self.Color_det_btn.setText(_translate("MainWindow", "1.3 Color Detection"))
        self.Blend_btn.setText(_translate("MainWindow", "1.4 Blending"))
        self.Img_smo_box.setTitle(_translate("MainWindow", "2. Image Smoothing"))
        self.Gau_btn.setText(_translate("MainWindow", "2.1 Gaussian Blur"))
        self.Bil_btn.setText(_translate("MainWindow", "2.2 Bilateral filter"))
        self.Med_btn.setText(_translate("MainWindow", "2.3 Median filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
