# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Img_Class_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Img_Class_box.setGeometry(QtCore.QRect(50, 80, 311, 371))
        self.Img_Class_box.setObjectName("Img_Class_box")
        self.Show_Img_btn = QtWidgets.QPushButton(self.Img_Class_box)
        self.Show_Img_btn.setGeometry(QtCore.QRect(30, 90, 251, 23))
        self.Show_Img_btn.setObjectName("Show_Img_btn")
        self.Show_mod_btn = QtWidgets.QPushButton(self.Img_Class_box)
        self.Show_mod_btn.setGeometry(QtCore.QRect(30, 130, 251, 23))
        self.Show_mod_btn.setObjectName("Show_mod_btn")
        self.Show_Dat_btn = QtWidgets.QPushButton(self.Img_Class_box)
        self.Show_Dat_btn.setGeometry(QtCore.QRect(30, 170, 251, 23))
        self.Show_Dat_btn.setObjectName("Show_Dat_btn")
        self.Load_Img_btn = QtWidgets.QPushButton(self.Img_Class_box)
        self.Load_Img_btn.setGeometry(QtCore.QRect(30, 50, 251, 23))
        self.Load_Img_btn.setObjectName("Load_Img_btn")
        self.Show_Accu_btn = QtWidgets.QPushButton(self.Img_Class_box)
        self.Show_Accu_btn.setGeometry(QtCore.QRect(30, 210, 251, 23))
        self.Show_Accu_btn.setObjectName("Show_Accu_btn")
        self.Infer_btn = QtWidgets.QPushButton(self.Img_Class_box)
        self.Infer_btn.setGeometry(QtCore.QRect(30, 250, 251, 23))
        self.Infer_btn.setObjectName("Infer_btn")
        self.Show_Img_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Show_Img_box.setGeometry(QtCore.QRect(390, 80, 321, 371))
        self.Show_Img_box.setTitle("")
        self.Show_Img_box.setObjectName("Show_Img_box")
        self.Img_lab = QtWidgets.QLabel(self.Show_Img_box)
        self.Img_lab.setGeometry(QtCore.QRect(50, 40, 224, 224))
        self.Img_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Img_lab.setObjectName("Img_lab")
        self.Class_lab = QtWidgets.QLabel(self.Show_Img_box)
        self.Class_lab.setGeometry(QtCore.QRect(60, 280, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Taipei Sans TC Beta")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Class_lab.setFont(font)
        self.Class_lab.setText("")
        self.Class_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Class_lab.setObjectName("Class_lab")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Img_Class_box.setTitle(_translate("MainWindow", "Image Classifier"))
        self.Show_Img_btn.setText(_translate("MainWindow", "1. Show Train Images"))
        self.Show_mod_btn.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.Show_Dat_btn.setText(_translate("MainWindow", "3. Show Data Augmentation"))
        self.Load_Img_btn.setText(_translate("MainWindow", "Load Image"))
        self.Show_Accu_btn.setText(_translate("MainWindow", "4. Show Accuracy and Loss"))
        self.Infer_btn.setText(_translate("MainWindow", "5. Inference"))
        self.Img_lab.setText(_translate("MainWindow", "Image label"))
