# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ResNet_box = QtWidgets.QGroupBox(self.centralwidget)
        self.ResNet_box.setGeometry(QtCore.QRect(30, 40, 221, 411))
        self.ResNet_box.setObjectName("ResNet_box")
        self.Load_img_btn = QtWidgets.QPushButton(self.ResNet_box)
        self.Load_img_btn.setGeometry(QtCore.QRect(30, 40, 171, 31))
        self.Load_img_btn.setObjectName("Load_img_btn")
        self.Show_img_btn = QtWidgets.QPushButton(self.ResNet_box)
        self.Show_img_btn.setGeometry(QtCore.QRect(30, 100, 171, 31))
        self.Show_img_btn.setObjectName("Show_img_btn")
        self.Show_dis_btn = QtWidgets.QPushButton(self.ResNet_box)
        self.Show_dis_btn.setGeometry(QtCore.QRect(30, 160, 171, 31))
        self.Show_dis_btn.setObjectName("Show_dis_btn")
        self.Show_mod_btn = QtWidgets.QPushButton(self.ResNet_box)
        self.Show_mod_btn.setGeometry(QtCore.QRect(30, 220, 171, 31))
        self.Show_mod_btn.setObjectName("Show_mod_btn")
        self.Show_cmp_btn = QtWidgets.QPushButton(self.ResNet_box)
        self.Show_cmp_btn.setGeometry(QtCore.QRect(30, 280, 171, 31))
        self.Show_cmp_btn.setObjectName("Show_cmp_btn")
        self.Inf_btn = QtWidgets.QPushButton(self.ResNet_box)
        self.Inf_btn.setGeometry(QtCore.QRect(30, 340, 171, 31))
        self.Inf_btn.setObjectName("Inf_btn")
        self.Img_lab = QtWidgets.QLabel(self.centralwidget)
        self.Img_lab.setGeometry(QtCore.QRect(320, 50, 331, 331))
        self.Img_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Img_lab.setObjectName("Img_lab")
        self.Res_lab = QtWidgets.QLabel(self.centralwidget)
        self.Res_lab.setGeometry(QtCore.QRect(290, 410, 391, 51))
        self.Res_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Res_lab.setObjectName("Res_lab")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ResNet_box.setTitle(_translate("MainWindow", "5. ResNet50"))
        self.Load_img_btn.setText(_translate("MainWindow", "Load Image"))
        self.Show_img_btn.setText(_translate("MainWindow", "1. Show Images"))
        self.Show_dis_btn.setText(_translate("MainWindow", "2. Show Distribution"))
        self.Show_mod_btn.setText(_translate("MainWindow", "3. Show Model Structure"))
        self.Show_cmp_btn.setText(_translate("MainWindow", "4. Show Comparison"))
        self.Inf_btn.setText(_translate("MainWindow", "5. Inference"))
        self.Img_lab.setText(_translate("MainWindow", "Image"))
        self.Res_lab.setText(_translate("MainWindow", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
